In [3]:
import openpyxl

# 读取原始xlsx文件
input_file_path = 'D://Desktop//dsProject//merged.xlsx'
output_file_path = 'D://Desktop//dsProject//output.xlsx'

# 打开工作簿
workbook = openpyxl.load_workbook(input_file_path)
sheet = workbook.active

# 创建新的工作簿用于保存分割后的数据
new_workbook = openpyxl.Workbook()
new_sheet = new_workbook.active

# 遍历原始表格的每一行
for row in sheet.iter_rows(values_only=True):
    new_row = []  # 用于保存分割后的整体
    for cell_value in row:
        parts = cell_value.split('_')  # 使用_进行分割
        new_row.extend(parts)  # 将分割后的部分添加到新行中
    new_sheet.append(new_row)  # 添加新行到新表格

# 保存新的xlsx文件
new_workbook.save(output_file_path)

print("分割完成并保存到新文件中。")

分割完成并保存到新文件中。


In [2]:
import pandas as pd
import os

# 指定包含xlsx文件的文件夹路径
folder_path = 'D://Desktop//dsProject'

# 获取文件夹中所有xlsx文件的路径
xlsx_files = [file for file in os.listdir(folder_path) if file.lower().endswith('.xlsx')]

# 创建一个空的DataFrame来保存合并后的数据
merged_data = pd.DataFrame()

# 遍历所有xlsx文件并将数据合并到DataFrame中
for xlsx_file in xlsx_files:
    file_path = os.path.join(folder_path, xlsx_file)
    df = pd.read_excel(file_path, header=None)  # 读取单列的数据
    merged_data = pd.concat([merged_data, df], axis=0)  # 在行方向上堆叠数据

# 保存合并后的数据到新的xlsx文件
output_file_path = os.path.join(folder_path, 'merged.xlsx')
merged_data.to_excel(output_file_path, index=False, header=False)

print("合并完成，数据保存到 merged.xlsx 文件中。")



合并完成，数据保存到 merged.xlsx 文件中。


In [1]:
import csv

# 输入文件路径和输出文件路径
input_file = 'D:\Desktop\SewerML_Train.csv'
output_file = 'D://Desktop//1.csv'

# 打开输入文件和输出文件
with open(input_file, 'r', newline='', encoding='utf-8') as infile, \
        open(output_file, 'w', newline='', encoding='utf-8') as outfile:

    reader = csv.reader(infile)
    writer = csv.writer(outfile)

    # 写入输出文件的列名（头部）
    headers = next(reader)
    writer.writerow(headers)

    # 遍历每一行数据
    for row in reader:
        # 提取标签列的值（第2到第8列）
        label_values = row[1:8]

        # 如果标签中只有一个1，则将这一行写入输出文件
        if label_values.count('1') == 1:
            writer.writerow(row)

print("已生成新文件，多个为1的标签行已删除。")


已生成新文件，多个为1的标签行已删除。


In [3]:
import os

import os

def get_file_names(directory, extension):
    file_names = []
    for filename in os.listdir(directory):
        if filename.endswith(extension):
            file_names.append(os.path.splitext(filename)[0])
    return file_names

def main():
    image_folder = "D:\Desktop\yolov5\data\images//val"
    txt_folder = "D:\Desktop\yolov5\data\labels//val"

    image_file_names = get_file_names(image_folder, ".jpg")  # 假设图片扩展名为jpg
    txt_file_names = get_file_names(txt_folder, ".txt")

    for image_file_name in image_file_names:
        if image_file_name not in txt_file_names:
            print(f"Deleting {image_file_name}.jpg")
            image_path = os.path.join(image_folder, image_file_name + ".jpg")
            if os.path.exists(image_path):
                os.remove(image_path)
            else:
                print(f"Image {image_file_name}.jpg not found.")

if __name__ == "__main__":
    main()


Deleting 1.jpg
Deleting 111.jpg
Deleting 17.jpg
Deleting 202003230000000.jpg
Deleting 202003230000339.jpg
Deleting 202003231000640.jpg
Deleting 202003362000049.jpg
Deleting 202003366000017.jpg
Deleting 202003439000000.jpg
Deleting 202003439000050.jpg
Deleting 202003445000810.jpg
Deleting 202003482000139.jpg
Deleting 2021030066000627.jpg
Deleting 2021030360000050.jpg
Deleting 2021030360000412.jpg
Deleting 2021040039000445.jpg
Deleting 2021040076001056.jpg
Deleting 2021050063000518.jpg
Deleting 2021050083000305.jpg
Deleting 2021050085001003.jpg
Deleting 2021050107000003.jpg
Deleting 2021050121000348.jpg
Deleting 2021050137001009.jpg
Deleting 2021050149000015.jpg
Deleting 2021050149000058.jpg
Deleting 2021050150000225.jpg
Deleting 2021050150000503.jpg
Deleting 2021050157000016.jpg
Deleting 2021050179000625.jpg
Deleting 27417.mp4_20230504_195559.379.jpg
Deleting 27417.mp4_20230504_195608.108.jpg
Deleting 27425.mp4_20230504_195752.427.jpg
Deleting 27466.mp4_20230504_195934.667.jpg
Deleting 

In [4]:
import os
import shutil

source_folder = r"D:\Desktop\1"
output_folder = r"D:\Desktop\RenamedImages"

if not os.path.exists(output_folder):
    os.makedirs(output_folder)

for root, dirs, files in os.walk(source_folder):
    for dir_name in dirs:
        dir_path = os.path.join(root, dir_name)
        image_files = [file for file in os.listdir(dir_path) if file.lower().endswith(('.png', '.jpg', '.jpeg'))]

        for index, image_file in enumerate(image_files):
            # Generate new name
            new_name = f"{dir_name}{index + 1}"

            # Get extension
            _, extension = os.path.splitext(image_file)

            # Combine new name with extension
            new_name_with_extension = f"{new_name}{extension}"

            # Source and destination paths
            source_path = os.path.join(dir_path, image_file)
            destination_path = os.path.join(output_folder, new_name_with_extension)

            # Copy the file with the new name to the output folder
            shutil.copy(source_path, destination_path)

            print(f"Renamed {image_file} to {new_name_with_extension}")


Renamed 00003368.png to AJ1.png
Renamed 00009724.png to AJ2.png
Renamed 00009740.png to AJ3.png
Renamed 00018703.png to AJ4.png
Renamed 00050028.png to AJ5.png
Renamed 00073987.png to AJ6.png
Renamed 00073994.png to AJ7.png
Renamed 00080344.png to AJ8.png
Renamed 00081808.png to AJ9.png
Renamed 00081817.png to AJ10.png
Renamed 00081825.png to AJ11.png
Renamed 00081840.png to AJ12.png
Renamed 00102925.png to AJ13.png
Renamed 00103138.png to AJ14.png
Renamed 00103140.png to AJ15.png
Renamed 01110379.png to AJ16.png
Renamed 01115783.png to AJ17.png
Renamed 01118546.png to AJ18.png
Renamed 01178092.png to AJ19.png
Renamed 01178227.png to AJ20.png
Renamed 01178258.png to AJ21.png
Renamed 01178342.png to AJ22.png
Renamed 01178343.png to AJ23.png
Renamed 01178364.png to AJ24.png
Renamed 01178365.png to AJ25.png
Renamed 01178416.png to AJ26.png
Renamed 01178417.png to AJ27.png
Renamed 01179122.png to AJ28.png
Renamed 01180871.png to AJ29.png
Renamed 01180872.png to AJ30.png
Renamed 01180876.pn

In [5]:
import os
import random
import shutil

source_folder = r"D:\Desktop\yolov5\data\images"
output_folder = r"D:\Desktop\yolov5\data\images"

train_ratio = 0.7
val_ratio = 0.2
test_ratio = 0.1

def move_files(files, destination_folder):
    if not os.path.exists(destination_folder):
        os.makedirs(destination_folder)

    for file in files:
        source_path = os.path.join(source_folder, file)
        destination_path = os.path.join(destination_folder, file)
        shutil.move(source_path, destination_path)
        print(f"Moved {file} to {destination_folder}")

# Get list of image files
image_files = [file for file in os.listdir(source_folder) if file.lower().endswith(('.png', '.jpg', '.jpeg'))]

# Shuffle the list of image files
random.shuffle(image_files)

# Calculate split points
num_files = len(image_files)
num_train = int(num_files * train_ratio)
num_val = int(num_files * val_ratio)
num_test = num_files - num_train - num_val

# Split image files
train_files = image_files[:num_train]
val_files = image_files[num_train:num_train+num_val]
test_files = image_files[num_train+num_val:]

# Move files to respective subfolders
move_files(train_files, os.path.join(output_folder, "train"))
move_files(val_files, os.path.join(output_folder, "val"))
move_files(test_files, os.path.join(output_folder, "test"))


Moved CJ58.jpg to D:\Desktop\yolov5\data\images\train
Moved BX70.jpg to D:\Desktop\yolov5\data\images\train
Moved AJ89.png to D:\Desktop\yolov5\data\images\train
Moved CJ98.jpg to D:\Desktop\yolov5\data\images\train
Moved CJ93.jpg to D:\Desktop\yolov5\data\images\train
Moved AJ141.png to D:\Desktop\yolov5\data\images\train
Moved BX48.jpg to D:\Desktop\yolov5\data\images\train
Moved CJ50.jpg to D:\Desktop\yolov5\data\images\train
Moved CK153.png to D:\Desktop\yolov5\data\images\train
Moved CK19.png to D:\Desktop\yolov5\data\images\train
Moved CK116.png to D:\Desktop\yolov5\data\images\train
Moved AJ182.jpg to D:\Desktop\yolov5\data\images\train
Moved AJ12.png to D:\Desktop\yolov5\data\images\train
Moved CJ104.jpg to D:\Desktop\yolov5\data\images\train
Moved AJ102.png to D:\Desktop\yolov5\data\images\train
Moved CK124.png to D:\Desktop\yolov5\data\images\train
Moved AJ85.png to D:\Desktop\yolov5\data\images\train
Moved CQ31.jpg to D:\Desktop\yolov5\data\images\train
Moved CQ63.jpg to D:\

In [1]:
import os

def find_unique_filenames(folder1_path, folder2_path):
    folder1_files = set()
    folder2_files = set()

    for root, dirs, files in os.walk(folder1_path):
        for file in files:
            file_name, _ = os.path.splitext(file)
            folder1_files.add(file_name)

    for root, dirs, files in os.walk(folder2_path):
        for file in files:
            file_name, _ = os.path.splitext(file)
            folder2_files.add(file_name)

    unique_in_folder1 = folder1_files - folder2_files
    unique_in_folder2 = folder2_files - folder1_files

    return unique_in_folder1, unique_in_folder2

if __name__ == "__main__":
    folder1_path = r"D:\Desktop\yolov5\yolov5\val\images"
    folder2_path = r"D:\Desktop\yolov5\yolov5\val\labels"
    unique_in_folder1, unique_in_folder2 = find_unique_filenames(folder1_path, folder2_path)

    print("在第一个文件夹中独有的文件名:")
    for filename in unique_in_folder1:
        print(filename)

    print("=" * 40)

    print("在第二个文件夹中独有的文件名:")
    for filename in unique_in_folder2:
        print(filename)


在第一个文件夹中独有的文件名:
ZC18
ZC21
ZC22
ZC23
ZC19
ZC20
在第二个文件夹中独有的文件名:
SL68
SG157
classes


In [4]:
import cv2
import numpy as np

# Load the image
image_path = 'D:\Desktop\AJ169.png'
image = cv2.imread(image_path)

# Convert the image to grayscale
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Apply edge detection to find the regions with strong edges (potential mosaics)
edges = cv2.Canny(gray_image, threshold1=30, threshold2=100)

# Find contours in the edges image
contours, _ = cv2.findContours(edges, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

# Create a copy of the original image to store the filled regions
filled_image = image.copy()

# Iterate through the detected contours
# Iterate through the detected contours
for contour in contours:
    # Calculate the bounding rectangle of the contour
    x, y, w, h = cv2.boundingRect(contour)

    # Extract the region from the original image
    mosaic_region = image[y:y+h, x:x+w]

    # Debugging: Print the dimensions of the mosaic region
    print(f"Mosaic Region Dimensions: {w} x {h}")

    # Resize the mosaic region for better visibility
    mosaic_region = cv2.resize(mosaic_region, (w//10, h//10), interpolation=cv2.INTER_NEAREST)

    # Fill the corresponding region in the filled image with the mosaic pattern
    filled_image[y:y+h, x:x+w] = mosaic_region

# Display the original image and the filled image
cv2.imshow('Original Image', image)
cv2.imshow('Filled Image', filled_image)
cv2.waitKey(0)
cv2.destroyAllWindows()


mosaic_region = cv2.resize(mosaic_region, (w//10, h//10), interpolation=cv2.INTER_NEAREST)
print(f"Original Width: {w}, Original Height: {h}")
target_width = w // 10
target_height = h // 10
print(f"Target Width: {target_width}, Target Height: {target_height}")
mosaic_region = cv2.resize(mosaic_region, (target_width, target_height), interpolation=cv2.INTER_NEAREST)


Mosaic Region Dimensions: 1 x 1


error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4065: error: (-215:Assertion failed) inv_scale_x > 0 in function 'cv::resize'


In [5]:
import os

def compare_and_delete_non_matching_files(folder1, folder2, subfolder_names):
    for subfolder_name in subfolder_names:
        subfolder_path1 = os.path.join(folder1, subfolder_name)
        subfolder_path2 = os.path.join(folder2, subfolder_name)

        if os.path.isdir(subfolder_path1) and os.path.isdir(subfolder_path2):
            files_subfolder1 = set(
                os.path.splitext(filename)[0] for filename in os.listdir(subfolder_path1)
            )
            files_subfolder2 = set(
                os.path.splitext(filename)[0] for filename in os.listdir(subfolder_path2)
            )

            files_to_delete_from_subfolder1 = files_subfolder1 - files_subfolder2

            for file_to_delete in files_to_delete_from_subfolder1:
                for filename in os.listdir(subfolder_path1):
                    if os.path.splitext(filename)[0] == file_to_delete:
                        file_path = os.path.join(subfolder_path1, filename)
                        if os.path.isfile(file_path):
                            os.remove(file_path)
                            print(f"删除文件: {file_path}")
                            break

if __name__ == "__main__":
    folder1_path = r"D:\研究生实验室\管道机器人\数据集\data_20230829\TL\images"  # 修改为文件夹1的路径
    folder2_path = r"D:\研究生实验室\管道机器人\数据集\data_20230829\TL\labels"  # 修改为文件夹2的路径
    subfolder_names = ["train", "val"]
    compare_and_delete_non_matching_files(r"D:\Desktop\data\images", r"D:\Desktop\data\labels", subfolder_names)
    # compare_and_delete_non_matching_files(r"D:\Desktop\data\labels", r"D:\Desktop\data\images", subfolder_names)

删除文件: D:\Desktop\data\images\train\ZC26.jpg


In [ ]:
import torch
from torch import nn
nn.Sequential

In [16]:
import torch
a = torch.randn(2,2,2)
b = torch.softmax(a, -1)
b

tensor([[[0.4564, 0.5436],
         [0.1094, 0.8906]],

        [[0.3959, 0.6041],
         [0.5284, 0.4716]]])

In [28]:
import torch
torch.manual_seed(42)
a = torch.randn(2,3,2)
print(a)
print("------------------------------")
# bb = torch.softmax(a, -1)
b = a.reshape(2,6)
print(b)

tensor([[[ 0.3367,  0.1288],
         [ 0.2345,  0.2303],
         [-1.1229, -0.1863]],

        [[ 2.2082, -0.6380],
         [ 0.4617,  0.2674],
         [ 0.5349,  0.8094]]])
------------------------------
tensor([[ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617,  0.2674,  0.5349,  0.8094]])


In [12]:
import torch
torch.manual_seed(42)
x1 = torch.randn(2,2,2)
x2 = torch.randn(2,2,2)
x3 = torch.randn(2,2,2)
x4 = torch.randn(2,2,2)
print("x1 = {} \r\nx2 = {} \r\nx3 = {}\r\nx4 = {}".format(x1, x2, x3, x4))
x = torch.cat((x1, x2, x3, x4), -1)
print("x = {}".format(x))

x1 = tensor([[[ 0.3367,  0.1288],
         [ 0.2345,  0.2303]],

        [[-1.1229, -0.1863],
         [ 2.2082, -0.6380]]]) 
x2 = tensor([[[ 0.4617,  0.2674],
         [ 0.5349,  0.8094]],

        [[ 1.1103, -1.6898],
         [-0.9890,  0.9580]]]) 
x3 = tensor([[[ 1.3221,  0.8172],
         [-0.7658, -0.7506]],

        [[ 1.3525,  0.6863],
         [-0.3278,  0.7950]]])
x4 = tensor([[[ 0.2815,  0.0562],
         [ 0.5227, -0.2384]],

        [[-0.0499,  0.5263],
         [-0.0085,  0.7291]]])
x = tensor([[[ 0.3367,  0.1288,  0.4617,  0.2674,  1.3221,  0.8172,  0.2815,
           0.0562],
         [ 0.2345,  0.2303,  0.5349,  0.8094, -0.7658, -0.7506,  0.5227,
          -0.2384]],

        [[-1.1229, -0.1863,  1.1103, -1.6898,  1.3525,  0.6863, -0.0499,
           0.5263],
         [ 2.2082, -0.6380, -0.9890,  0.9580, -0.3278,  0.7950, -0.0085,
           0.7291]]])


In [27]:
import torch
coords_h = torch.arange(5)
coords_w = torch.arange(5)
coords = torch.stack(torch.meshgrid([coords_h, coords_w], indexing="ij"))
print("coords is {}".format(coords))
coords_flatten = torch.flatten(coords, 1)
print('------------------------------------------------------')
print("coords_flatten is {}".format(coords_flatten))


coords is tensor([[[0, 0, 0, 0, 0],
         [1, 1, 1, 1, 1],
         [2, 2, 2, 2, 2],
         [3, 3, 3, 3, 3],
         [4, 4, 4, 4, 4]],

        [[0, 1, 2, 3, 4],
         [0, 1, 2, 3, 4],
         [0, 1, 2, 3, 4],
         [0, 1, 2, 3, 4],
         [0, 1, 2, 3, 4]]])
------------------------------------------------------
coords_flatten is tensor([[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4,
         4],
        [0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3,
         4]])


In [29]:
print("coords_flatten[:, :, None] is {}".format(coords_flatten[:, :, None]))

coords_flatten[:, :, None] is tensor([[[0],
         [0],
         [0],
         [0],
         [0],
         [1],
         [1],
         [1],
         [1],
         [1],
         [2],
         [2],
         [2],
         [2],
         [2],
         [3],
         [3],
         [3],
         [3],
         [3],
         [4],
         [4],
         [4],
         [4],
         [4]],

        [[0],
         [1],
         [2],
         [3],
         [4],
         [0],
         [1],
         [2],
         [3],
         [4],
         [0],
         [1],
         [2],
         [3],
         [4],
         [0],
         [1],
         [2],
         [3],
         [4],
         [0],
         [1],
         [2],
         [3],
         [4]]])


In [30]:
print("coords_flatten[:, :, None] is {}".format(coords_flatten[:, None, :]))

coords_flatten[:, :, None] is tensor([[[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4,
          4, 4]],

        [[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2,
          3, 4]]])


In [19]:
import torch
torch.random.manual_seed(42)
a = torch.randn(3,4)
a

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380],
        [ 0.4617,  0.2674,  0.5349,  0.8094]])

In [22]:
b = [1, 2, 1, 0, 1, 1]
b = torch.tensor(b)
b.shape

torch.Size([6])

In [23]:
a[b]

tensor([[-1.1229, -0.1863,  2.2082, -0.6380],
        [ 0.4617,  0.2674,  0.5349,  0.8094],
        [-1.1229, -0.1863,  2.2082, -0.6380],
        [ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380],
        [-1.1229, -0.1863,  2.2082, -0.6380]])

In [27]:
6 % 7

6

In [30]:
aa = a.unsqueeze(1)
aa

tensor([[[ 0.3367,  0.1288,  0.2345,  0.2303]],

        [[-1.1229, -0.1863,  2.2082, -0.6380]],

        [[ 0.4617,  0.2674,  0.5349,  0.8094]]])

In [31]:
bb = a.unsqueeze(2)
bb

tensor([[[ 0.3367],
         [ 0.1288],
         [ 0.2345],
         [ 0.2303]],

        [[-1.1229],
         [-0.1863],
         [ 2.2082],
         [-0.6380]],

        [[ 0.4617],
         [ 0.2674],
         [ 0.5349],
         [ 0.8094]]])

In [32]:
aa - bb

tensor([[[ 0.0000, -0.2079, -0.1022, -0.1064],
         [ 0.2079,  0.0000,  0.1057,  0.1015],
         [ 0.1022, -0.1057,  0.0000, -0.0041],
         [ 0.1064, -0.1015,  0.0041,  0.0000]],

        [[ 0.0000,  0.9365,  3.3311,  0.4849],
         [-0.9365,  0.0000,  2.3945, -0.4517],
         [-3.3311, -2.3945,  0.0000, -2.8462],
         [-0.4849,  0.4517,  2.8462,  0.0000]],

        [[ 0.0000, -0.1943,  0.0732,  0.3477],
         [ 0.1943,  0.0000,  0.2676,  0.5420],
         [-0.0732, -0.2676,  0.0000,  0.2745],
         [-0.3477, -0.5420, -0.2745,  0.0000]]])

In [33]:
"""
YOLO 格式的数据集转化为 COCO 格式的数据集
--root_dir 输入根路径
--save_path 保存文件的名字(没有random_split时使用)
--random_split 有则会随机划分数据集，然后再分别保存为3个文件。
--split_by_file 按照 ./train.txt ./val.txt ./test.txt 来对数据集进行划分。
"""

import os
import cv2
import json
from tqdm import tqdm
from sklearn.model_selection import train_test_split
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--root_dir', default='./data',type=str, help="root path of images and labels, include ./images and ./labels and classes.txt")
parser.add_argument('--save_path', type=str,default='./train.json', help="if not split the dataset, give a path to a json file")
parser.add_argument('--random_split', action='store_true', help="random split the dataset, default ratio is 8:1:1")
parser.add_argument('--split_by_file', action='store_true', help="define how to split the dataset, include ./train.txt ./val.txt ./test.txt ")

arg = parser.parse_args()

def train_test_val_split_random(img_paths,ratio_train=0.8,ratio_test=0.1,ratio_val=0.1):
    # 这里可以修改数据集划分的比例。
    assert int(ratio_train+ratio_test+ratio_val) == 1
    train_img, middle_img = train_test_split(img_paths,test_size=1-ratio_train, random_state=233)
    ratio=ratio_val/(1-ratio_train)
    val_img, test_img  =train_test_split(middle_img,test_size=ratio, random_state=233)
    print("NUMS of train:val:test = {}:{}:{}".format(len(train_img), len(val_img), len(test_img)))
    return train_img, val_img, test_img

def train_test_val_split_by_files(img_paths, root_dir):
    # 根据文件 train.txt, val.txt, test.txt（里面写的都是对应集合的图片名字） 来定义训练集、验证集和测试集
    phases = ['train', 'val', 'test']
    img_split = []
    for p in phases:
        define_path = os.path.join(root_dir, f'{p}.txt')
        print(f'Read {p} dataset definition from {define_path}')
        assert os.path.exists(define_path)
        with open(define_path, 'r') as f:
            img_paths = f.readlines()
            # img_paths = [os.path.split(img_path.strip())[1] for img_path in img_paths]  # NOTE 取消这句备注可以读取绝对地址。
            img_split.append(img_paths)
    return img_split[0], img_split[1], img_split[2]


def yolo2coco(arg):
    root_path = arg.root_dir
    print("Loading data from ",root_path)

    assert os.path.exists(root_path)
    originLabelsDir = os.path.join(root_path, 'labels')
    originImagesDir = os.path.join(root_path, 'images')
    with open(os.path.join(root_path, 'classes.txt')) as f:
        classes = f.read().strip().split()
    # images dir name
    indexes = os.listdir(originImagesDir)

    if arg.random_split or arg.split_by_file:
        # 用于保存所有数据的图片信息和标注信息
        train_dataset = {'categories': [], 'annotations': [], 'images': []}
        val_dataset = {'categories': [], 'annotations': [], 'images': []}
        test_dataset = {'categories': [], 'annotations': [], 'images': []}

        # 建立类别标签和数字id的对应关系, 类别id从0开始。
        for i, cls in enumerate(classes, 0):
            train_dataset['categories'].append({'id': i, 'name': cls, 'supercategory': 'mark'})
            val_dataset['categories'].append({'id': i, 'name': cls, 'supercategory': 'mark'})
            test_dataset['categories'].append({'id': i, 'name': cls, 'supercategory': 'mark'})

        if arg.random_split:
            print("spliting mode: random split")
            train_img, val_img, test_img = train_test_val_split_random(indexes,0.8,0.1,0.1)
        elif arg.split_by_file:
            print("spliting mode: split by files")
            train_img, val_img, test_img = train_test_val_split_by_files(indexes, root_path)
    else:
        dataset = {'categories': [], 'annotations': [], 'images': []}
        for i, cls in enumerate(classes, 0):
            dataset['categories'].append({'id': i, 'name': cls, 'supercategory': 'mark'})

    # 标注的id
    ann_id_cnt = 0
    for k, index in enumerate(tqdm(indexes)):
        # 支持 png jpg 格式的图片。
        txtFile = index.replace('images','txt').replace('.jpg','.txt').replace('.png','.txt')
        # 读取图像的宽和高
        im = cv2.imread(os.path.join(root_path, 'images/') + index)
        height, width, _ = im.shape
        if arg.random_split or arg.split_by_file:
            # 切换dataset的引用对象，从而划分数据集
            if index in train_img:
                dataset = train_dataset
            elif index in val_img:
                dataset = val_dataset
            elif index in test_img:
                dataset = test_dataset
        # 添加图像的信息
        dataset['images'].append({'file_name': index,
                                  'id': k,
                                  'width': width,
                                  'height': height})
        if not os.path.exists(os.path.join(originLabelsDir, txtFile)):
            # 如没标签，跳过，只保留图片信息。
            continue
        with open(os.path.join(originLabelsDir, txtFile), 'r') as fr:
            labelList = fr.readlines()
            for label in labelList:
                label = label.strip().split()
                x = float(label[1])
                y = float(label[2])
                w = float(label[3])
                h = float(label[4])

                # convert x,y,w,h to x1,y1,x2,y2
                H, W, _ = im.shape
                x1 = (x - w / 2) * W
                y1 = (y - h / 2) * H
                x2 = (x + w / 2) * W
                y2 = (y + h / 2) * H
                # 标签序号从0开始计算, coco2017数据集标号混乱，不管它了。
                cls_id = int(label[0])
                width = max(0, x2 - x1)
                height = max(0, y2 - y1)
                dataset['annotations'].append({
                    'area': width * height,
                    'bbox': [x1, y1, width, height],
                    'category_id': cls_id,
                    'id': ann_id_cnt,
                    'image_id': k,
                    'iscrowd': 0,
                    # mask, 矩形是从左上角点按顺时针的四个顶点
                    'segmentation': [[x1, y1, x2, y1, x2, y2, x1, y2]]
                })
                ann_id_cnt += 1

    # 保存结果
    folder = os.path.join(root_path, 'annotations')
    if not os.path.exists(folder):
        os.makedirs(folder)
    if arg.random_split or arg.split_by_file:
        for phase in ['train','val','test']:
            json_name = os.path.join(root_path, 'annotations/{}.json'.format(phase))
            with open(json_name, 'w') as f:
                if phase == 'train':
                    json.dump(train_dataset, f)
                elif phase == 'val':
                    json.dump(val_dataset, f)
                elif phase == 'test':
                    json.dump(test_dataset, f)
            print('Save annotation to {}'.format(json_name))
    else:
        json_name = os.path.join(root_path, 'annotations/{}'.format(arg.save_path))
        with open(json_name, 'w') as f:
            json.dump(dataset, f)
            print('Save annotation to {}'.format(json_name))

if __name__ == "__main__":

    yolo2coco(arg)

FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Desktop\\data\\labels\\train\\1_TL1.png.txt'